// ── API Authentication ──
//
// Three auth methods:
// 1. Static API key (BUFF_API_KEY env var) — admin
// 2. Wallet-derived API key (from /api/keys/generate) — agents/platforms
// 3. Wallet signature headers — direct wallet auth
//
// Header: x-api-key: <key>
// OR
// Header: x-wallet: <base58-pubkey>  +  x-signature: <base64-signature>

import { NextResponse } from "next/server";
import { createHmac } from "crypto";

const AUTH_MESSAGE = "Buff API Authentication";

/** Generate a deterministic API key for a wallet address */
export function deriveApiKey(wallet: string): string {
  const secret = process.env.BUFF_KEY_SECRET || process.env.BUFF_API_KEY || "buff-default-secret";
  return createHmac("sha256", secret)
    .update(`buff-api-key:${wallet}`)
    .digest("hex");
}

export function requireAuth(req: Request): NextResponse | null {
  const providedKey = req.headers.get("x-api-key");

  // Method 1: Static admin API key
  const adminKey = process.env.BUFF_API_KEY?.trim();
  if (providedKey && adminKey && providedKey === adminKey) {
    return null;
  }

  // Method 2: Wallet-derived API key
  // The caller must also send x-wallet so we can verify the key
  if (providedKey && providedKey !== adminKey) {
    const wallet = req.headers.get("x-wallet");
    if (wallet) {
      const expectedKey = deriveApiKey(wallet);
      if (providedKey === expectedKey) {
        return null;
      }
    }

    // Also allow derived keys without x-wallet header by checking against
    // all possible keys — but since that's not feasible, we accept any
    // 64-char hex key that was generated by our HMAC (admin key is also 64-char hex)
    // For security, wallet-derived keys REQUIRE x-wallet header.
    return NextResponse.json(
      { ok: false, error: "Invalid API key. Wallet-derived keys require x-wallet header." },
      { status: 403 }
    );
  }

  // Method 3: Wallet signature
  const wallet = req.headers.get("x-wallet");
  const signature = req.headers.get("x-signature");

  if (wallet && signature) {
    try {
      const { PublicKey } = require("@solana/web3.js");
      const nacl = require("tweetnacl");

      const pubkey = new PublicKey(wallet);
      const message = new TextEncoder().encode(AUTH_MESSAGE);
      const sigBytes = Buffer.from(signature, "base64");

      const valid = nacl.sign.detached.verify(
        message,
        sigBytes,
        pubkey.toBytes()
      );

      if (valid) return null;

      return NextResponse.json(
        { ok: false, error: "Invalid signature" },
        { status: 403 }
      );
    } catch {
      return NextResponse.json(
        { ok: false, error: "Invalid wallet or signature format" },
        { status: 400 }
      );
    }
  }

  return NextResponse.json(
    {
      ok: false,
      error: "Auth required. Use x-api-key OR x-wallet + x-signature headers.",
    },
    { status: 401 }
  );
}

export function getAuthMessage(): string {
  return AUTH_MESSAGE;
}
